### ISSUE TITLE
TypeError: Cannot read property 'Decimal128' of null

### ISSUE THREAD

**Issue by hugomallet** [alonronin/mockingoose#55]
Hello,

I have this error when i try to use mockingoose and mock a dependency using jest.mock('...')

The full stack trace :

```sh
TypeError: Cannot read property 'Decimal128' of null

      at Object.<anonymous> (node_modules/mongoose/lib/types/decimal128.js:13:44)
      at Object.<anonymous> (node_modules/mongoose/lib/utils.js:7:17)
      at Object.<anonymous> (node_modules/mongoose/lib/statemachine.js:8:15)
      at Object.<anonymous> (node_modules/mongoose/lib/internal.js:7:22)
```

**Comment by maximilianocatarino** [comment]
Same for me.

**Comment by alonronin** [comment]
@maximilianocatarino can you provide an example repo reproducing this?

**Comment by alonronin** [comment]
i'm closing this issue, please provide an example repo with this use case isolated.
