### ISSUE TITLE
ReferenceError: jest is not defined

### ISSUE THREAD

**Issue by subhashdike** [alonronin/mockingoose#56]
I am trying to use this module, and all I have is a single line in my code 

`const mockingoose = require('mockingoose').default;`

And my package json is something like this
```

"dependencies": {
    "mockingoose": "^2.13.2",
    "mongoose": "^5.7.7"
  },
  "devDependencies": {
    "jest": "^24.9.0"
  }
```

And the error I got is talking jest is not defined. I am not sure if I needed to, but did install jest myself. 

```
/src/samples/node-express/node_modules/mockingoose/lib/index.js:16
mongoose.connect = jest
                   ^

ReferenceError: jest is not defined
    at Object.<anonymous> (/src/samples/node-express/node_modules/mockingoose/lib/index.js:16:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/src/samples/node-express/test.js:1:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
```

**Comment by jwoodmansey** [comment]
Unlikely but... I had this when I was accidentally running my tests using mocha instead of jest. 🙃

**Comment by alonronin** [comment]
you need to run it in Jest runner only 😄 

btw, it should be a dev dependency.
